In [2]:
import open3d as o3d 
import numpy as np
from pathlib import Path

In [3]:
# get data base path to collect the point clouds
BASE = Path().resolve().parents[1]
DATA_PATH = BASE / 'data'
print(DATA_PATH)
SHOW_PC = True

/home/dayoff/codes/point_cloud_lib/data


In [4]:
# get first point cloud, assign it with a blue color
pc_path = DATA_PATH / 'kitti' / '0000000000.ply'
pcd = o3d.io.read_point_cloud(str(pc_path), format='ply')
pcd_size = len(np.asarray(pcd.points))

# define point cloud color
blue_color = [0, 0, 255]
np_colors = np.array([blue_color for _ in range(pcd_size)])
pcd.colors = o3d.utility.Vector3dVector(np_colors)

# show point cloud info
print('PCD:\n', pcd, '\n', 'PCD size: ', pcd_size, '\n', '\nPCD colors: \n', np.asarray(pcd.colors), '\n', '\nPCD points:\n', np.asarray(pcd.points))

PCD:
 geometry::PointCloud with 120574 points. 
 PCD size:  120574 
 
PCD colors: 
 [[  0.   0. 255.]
 [  0.   0. 255.]
 [  0.   0. 255.]
 ...
 [  0.   0. 255.]
 [  0.   0. 255.]
 [  0.   0. 255.]] 
 
PCD points:
 [[74.536  9.937  2.752]
 [74.558 10.178  2.754]
 [74.569 10.419  2.755]
 ...
 [ 3.705 -1.394 -1.73 ]
 [ 3.611 -1.345 -1.681]
 [ 3.73  -1.377 -1.738]]


In [11]:
if SHOW_PC:
    o3d.visualization.draw_geometries([pcd])

In [13]:
sorted_pcd = np.asarray(pcd.points)  # get all points from point cloud
idx_sorted_pdc = np.lexsort((sorted_pcd[:,1], sorted_pcd[:,0]))  # sort the coordinates array
new_pcd = o3d.geometry.PointCloud()
# create new point cloud out of these sorted point
new_pcd.points = o3d.utility.Vector3dVector(sorted_pcd[idx_sorted_pdc])  
# assign same color to the sorted point cloud
new_pcd.colors = o3d.utility.Vector3dVector(np_colors)  

In [14]:
np.asarray(new_pcd.points).shape == np.asarray(pcd.points).shape

True

In [15]:
if SHOW_PC:
    o3d.visualization.draw_geometries([new_pcd])

In [6]:
# get second point cloud, assign it with a red color
pc_path = DATA_PATH / 'kitti' / '0000000001.ply'
pcd_2 = o3d.io.read_point_cloud(str(pc_path), format='ply')
pcd_2_size = len(np.asarray(pcd_2.points))

# define point cloud color
red_color = [255, 0, 0]
np_colors_2 = np.array([red_color for _ in range(pcd_2_size)])
pcd_2.colors = o3d.utility.Vector3dVector(np_colors_2)

# show point cloud info
print('PCD 2:\n', pcd_2, '\n', 'PCD 2 size: ', pcd_2_size, '\n', '\nPCD 2 colors: \n', np.asarray(pcd_2.colors), '\n', '\nPCD 2 points:\n', np.asarray(pcd_2.points))

PCD 2:
 geometry::PointCloud with 120831 points. 
 PCD 2 size:  120831 
 
PCD 2 colors: 
 [[255.   0.   0.]
 [255.   0.   0.]
 [255.   0.   0.]
 ...
 [255.   0.   0.]
 [255.   0.   0.]
 [255.   0.   0.]] 
 
PCD 2 points:
 [[79.222  9.426  2.907]
 [73.181  9.99   2.707]
 [73.124 10.216  2.706]
 ...
 [ 3.692 -1.396 -1.725]
 [ 3.71  -1.39  -1.731]
 [ 3.721 -1.381 -1.735]]


In [133]:
if SHOW_PC:
    o3d.visualization.draw_geometries([pcd_2])

In [7]:
sorted_pcd_2 = np.asarray(pcd_2.points)  # get all points from point cloud
idx_sorted_pdc_2 = np.lexsort((sorted_pcd_2[:,1], sorted_pcd_2[:,0]))  # sort the coordinates array
new_pcd_2 = o3d.geometry.PointCloud()
# create new point cloud out of these sorted point
new_pcd_2.points = o3d.utility.Vector3dVector(sorted_pcd_2[idx_sorted_pdc_2])  
# assign same color to the sorted point cloud
new_pcd_2.colors = o3d.utility.Vector3dVector(np_colors_2)  

In [8]:
np.asarray(new_pcd_2.points).shape == np.asarray(pcd_2.points).shape

True

In [136]:
if SHOW_PC:
    o3d.visualization.draw_geometries([new_pcd_2])

In [9]:
# offset the second point cloud to visualize it more clearly when both point clouds are plot
offset_pcd_2 = o3d.geometry.PointCloud(new_pcd_2)
offset_pcd_2.points = o3d.utility.Vector3dVector(np.asarray(offset_pcd_2.points) + [0.0, 0.0, -10.0])
# assign same color to the offset point cloud
offset_pcd_2.colors = o3d.utility.Vector3dVector(np_colors_2)  

In [10]:
if SHOW_PC:
    # show both point clouds:
    # the first one is the first point cloud
    # the second one is the second point cloud
    o3d.visualization.draw_geometries([pcd, offset_pcd_2])

In [139]:
# get common coordinates
pcd_arr, pcd_2_arr = np.asarray(new_pcd.points), np.asarray(new_pcd_2.points)
# get unique points from both point clouds
pcd_set, pcd_2_set = set(map(tuple, pcd_arr)), set(map(tuple, pcd_2_arr))
# op & returns the intersection of the point clouds
intersec_arr = list(pcd_set & pcd_2_set)
intersec_np = np.array(intersec_arr)  # transform to a numpy array
print('Intersection between PC 1 and PC 2:', intersec_np.shape, '\nPC 1 size:\n', pcd_arr.shape, '\nPC 2 size:\n', pcd_2_arr.shape)

Intersection between PC 1 and PC 2: (173, 3) 
PC 1 size:
 (120574, 3) 
PC 2 size:
 (121604, 3)


In [140]:
# transform the intersection points found into a point cloud format
intersec_pc = o3d.geometry.PointCloud()
intersec_pc.points = o3d.utility.Vector3dVector(intersec_np)
intersec_pc_size = len(np.asarray(intersec_pc.points))

# define point cloud color
green_color = [0, 255, 0]
np_colors_3 = np.array([red_color for _ in range(intersec_pc_size)])

# offset this new point cloud to visualize clearly comparing to pc 1 and pc 2
intersec_pc_offset = o3d.geometry.PointCloud()
intersec_pc_offset.points = o3d.utility.Vector3dVector(np.asarray(intersec_pc.points) + [0.0, 0.0, -20.0])
intersec_pc_offset.colors = o3d.utility.Vector3dVector(np_colors_3)

In [141]:
if SHOW_PC:
    # show both point clouds and the intersection between them:
    # the first map is the first point cloud
    # the second map is the second point cloud
    # the third map is intersection between both point clouds
    o3d.visualization.draw_geometries([pcd, offset_pcd_2, intersec_pc_offset])