In [1]:
import open3d as o3d 
import numpy as np
from pathlib import Path
from math import sin, cos, sqrt, atan2, radians
import mpu

In [2]:
# get data base path to collect the point clouds
BASE = Path().resolve().parents[1]
DATA_PATH = BASE / 'data'
print(DATA_PATH)
SHOW_PC = True
TO_INTEGER = True

/home/dayoff/codes/point_cloud_lib/data


In [3]:
# get first point cloud, assign it with a blue color
pc_path = DATA_PATH / 'kitti' / '0000000000.ply'
pcd = o3d.io.read_point_cloud(str(pc_path), format='ply')
pcd_size = len(np.asarray(pcd.points))

# define point cloud color
blue_color = [0, 0, 255]
np_colors = np.array([blue_color for _ in range(pcd_size)])
pcd.colors = o3d.utility.Vector3dVector(np_colors)

# show point cloud info
print('PCD:\n', pcd, '\n', 'PCD size: ', pcd_size, '\n', '\nPCD colors: \n', np.asarray(pcd.colors), '\n', '\nPCD points:\n', np.asarray(pcd.points))

PCD:
 geometry::PointCloud with 120574 points. 
 PCD size:  120574 
 
PCD colors: 
 [[  0.   0. 255.]
 [  0.   0. 255.]
 [  0.   0. 255.]
 ...
 [  0.   0. 255.]
 [  0.   0. 255.]
 [  0.   0. 255.]] 
 
PCD points:
 [[74.536  9.937  2.752]
 [74.558 10.178  2.754]
 [74.569 10.419  2.755]
 ...
 [ 3.705 -1.394 -1.73 ]
 [ 3.611 -1.345 -1.681]
 [ 3.73  -1.377 -1.738]]


In [127]:
if SHOW_PC:
    o3d.visualization.draw_geometries([pcd])

In [4]:
if TO_INTEGER:
    # transform pc floats to pc integers
    int_pt_list = np.unique(np.asarray(pcd.points).astype(int), axis=0)

    int_pt_pc = o3d.geometry.PointCloud()
    int_pt_pc.points = o3d.utility.Vector3dVector(int_pt_list)
    int_pt_pc_size = len(np.asarray(int_pt_pc.points))

    # define point cloud color
    np_colors_3 = np.array([[0, 0, 0] for _ in range(int_pt_pc_size)])
    int_pt_pc.colors = o3d.utility.Vector3dVector(np_colors_3)

    # show point cloud info
    idx = 'int_pc'
    print(f'PCD {idx}:\n', int_pt_pc, f'\nPCD {idx} size: ', int_pt_pc_size, f'\n\nPCD {idx} colors: \n', np.asarray(int_pt_pc.colors), f'\n\nPCD {idx} points:\n', np.asarray(int_pt_pc.points))

PCD int_pc:
 geometry::PointCloud with 4300 points. 
PCD int_pc size:  4300 

PCD int_pc colors: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

PCD int_pc points:
 [[-77. -15.  -2.]
 [-77. -15.  -1.]
 [-77. -15.   0.]
 ...
 [ 76. -11.   2.]
 [ 76.   2.   0.]
 [ 76.   9.   0.]]


In [5]:
if TO_INTEGER and SHOW_PC:
    o3d.visualization.draw_geometries([int_pt_pc])

In [137]:
# get second point cloud, assign it with a red color
pc_path = DATA_PATH / 'kitti' / '0000000001.ply'
pcd_2 = o3d.io.read_point_cloud(str(pc_path), format='ply')
pcd_2_size = len(np.asarray(pcd_2.points))

# define point cloud color
red_color = [255, 0, 0]
np_colors_2 = np.array([red_color for _ in range(pcd_2_size)])
pcd_2.colors = o3d.utility.Vector3dVector(np_colors_2)

# show point cloud info
print('PCD 2:\n', pcd_2, '\n', 'PCD 2 size: ', pcd_2_size, '\n', '\nPCD 2 colors: \n', np.asarray(pcd_2.colors), '\n', '\nPCD 2 points:\n', np.asarray(pcd_2.points))

PCD 2:
 geometry::PointCloud with 120831 points. 
 PCD 2 size:  120831 
 
PCD 2 colors: 
 [[255.   0.   0.]
 [255.   0.   0.]
 [255.   0.   0.]
 ...
 [255.   0.   0.]
 [255.   0.   0.]
 [255.   0.   0.]] 
 
PCD 2 points:
 [[79.222  9.426  2.907]
 [73.181  9.99   2.707]
 [73.124 10.216  2.706]
 ...
 [ 3.692 -1.396 -1.725]
 [ 3.71  -1.39  -1.731]
 [ 3.721 -1.381 -1.735]]


In [133]:
if SHOW_PC:
    o3d.visualization.draw_geometries([pcd_2])

In [76]:
# get third point cloud, assign it with a red color
pc_path = DATA_PATH / 'kitti' / '0000000002.ply'
pcd_3 = o3d.io.read_point_cloud(str(pc_path), format='ply')
pcd_3_size = len(np.asarray(pcd_3.points))

# define point cloud color
red_color = [255, 0, 0]
np_colors_3 = np.array([red_color for _ in range(pcd_3_size)])
pcd_3.colors = o3d.utility.Vector3dVector(np_colors_3)

# show point cloud info
idx = 3
print(f'PCD {idx}:\n', pcd_3, f'\nPCD {idx} size: ', pcd_3_size, f'\n\nPCD {idx} colors: \n', np.asarray(pcd_3.colors), f'\n\nPCD {idx} points:\n', np.asarray(pcd_3.points))

PCD 3:
 geometry::PointCloud with 121015 points. 
PCD 3 size:  121015 

PCD 3 colors: 
 [[255.   0.   0.]
 [255.   0.   0.]
 [255.   0.   0.]
 ...
 [255.   0.   0.]
 [255.   0.   0.]
 [255.   0.   0.]] 

PCD 3 points:
 [[78.372  8.078  2.873]
 [77.816  9.63   2.861]
 [71.744 10.138  2.659]
 ...
 [ 3.712 -1.397 -1.733]
 [ 3.723 -1.388 -1.737]
 [ 3.737 -1.38  -1.742]]


In [107]:
# get third point cloud, assign it with a red color
pc_path = DATA_PATH / 'kitti' / '0000000003.ply'
pcd_4 = o3d.io.read_point_cloud(str(pc_path), format='ply')
pcd_4_size = len(np.asarray(pcd_4.points))

# define point cloud color
red_color = [255, 0, 0]
np_colors_4 = np.array([red_color for _ in range(pcd_4_size)])
pcd_4.colors = o3d.utility.Vector3dVector(np_colors_4)

# show point cloud info
idx = 4
print(f'PCD {idx}:\n', pcd_4, f'\nPCD {idx} size: ', pcd_4_size, f'\n\nPCD {idx} colors: \n', np.asarray(pcd_4.colors), f'\n\nPCD {idx} points:\n', np.asarray(pcd_4.points))

PCD 4:
 geometry::PointCloud with 121151 points. 
PCD 4 size:  121151 

PCD 4 colors: 
 [[255.   0.   0.]
 [255.   0.   0.]
 [255.   0.   0.]
 ...
 [255.   0.   0.]
 [255.   0.   0.]
 [255.   0.   0.]] 

PCD 4 points:
 [[76.994  8.302  2.828]
 [77.093  9.417  2.835]
 [76.718  9.616  2.824]
 ...
 [ 3.706 -1.402 -1.731]
 [ 3.705 -1.388 -1.729]
 [ 3.715 -1.378 -1.731]]


In [138]:
# calculate diff meters between pc 1 and pc 2 
lat1, lon1 = radians(49.015019172077), radians(8.4343357035849)  # pc 1
lat2, lon2 = radians(49.015012999213), radians(8.4343202373229)  # pc 2

dist = mpu.haversine_distance((lat1, lon1), (lat2, lon2))
print("Haversine Result (km):", dist)
dist_m_1 = dist * 1000
print("Haversine Result (m):", dist_m_1)
print("Haversine Result (cm):", dist * 100000)

Haversine Result (km): 3.2314911013966545e-05
Haversine Result (m): 0.032314911013966545
Haversine Result (cm): 3.2314911013966543


In [139]:
# calculate diff meters between pc 1 and pc 3 
lat1, lon1 = radians(49.015019172077), radians(8.4343357035849)  # pc 1
lat2, lon2 = radians(49.015006875378), radians(8.4343048069014)  # pc 3

dist = mpu.haversine_distance((lat1, lon1), (lat2, lon2))
print("Haversine Result (km):", dist)
dist_m_2 = dist * 1000
print("Haversine Result (m):", dist_m_2)
print("Haversine Result (cm):", dist * 100000)

Haversine Result (km): 6.4529985008487e-05
Haversine Result (m): 0.064529985008487
Haversine Result (cm): 6.452998500848699


In [140]:
# calculate diff meters between pc 1 and pc 4
lat1, lon1 = radians(49.015019172077), radians(8.4343357035849)  # pc 1
lat2, lon2 = radians(49.015000785305), radians(8.4342893959519)  # pc 4

dist = mpu.haversine_distance((lat1, lon1), (lat2, lon2))
print("Haversine Result (km):", dist)
dist_m_3 = dist * 1000
print("Haversine Result (m):", dist_m_3)
print("Haversine Result (cm):", dist * 100000)

Haversine Result (km): 9.668576778921812e-05
Haversine Result (m): 0.09668576778921813
Haversine Result (cm): 9.668576778921812


In [84]:
# offset the second point cloud + distance from the first
offset_pc_2_dist = o3d.geometry.PointCloud(pcd_2)
offset_pc_2_dist.points = o3d.utility.Vector3dVector(np.asarray(offset_pc_2_dist.points) + [dist_m_1, 0.0, 0.0])
offset_pc_2_dist_size = len(np.asarray(offset_pc_2_dist.points))

# define point cloud color
green_color = [0, 255, 0]
np_colors_3 = np.array([green_color for _ in range(offset_pc_2_dist_size)])
offset_pc_2_dist.colors = o3d.utility.Vector3dVector(np_colors_3)

In [104]:
# offset the third point cloud + distance from the second
offset_pc_3_dist = o3d.geometry.PointCloud(pcd_3)
offset_pc_3_dist.points = o3d.utility.Vector3dVector(np.asarray(offset_pc_3_dist.points) + [dist_m_2, 0.0, 0.0])
offset_pc_3_dist_size = len(np.asarray(offset_pc_3_dist.points))

# define point cloud color
green_color = [0, 0, 255]
np_colors_3 = np.array([green_color for _ in range(offset_pc_3_dist_size)])
offset_pc_3_dist.colors = o3d.utility.Vector3dVector(np_colors_3)

In [124]:
# offset the third point cloud + distance from the second
offset_pc_4_dist = o3d.geometry.PointCloud(pcd_4)
offset_pc_4_dist.points = o3d.utility.Vector3dVector(np.asarray(offset_pc_4_dist.points) + [2.8, 0.0, 0.0])
offset_pc_4_dist_size = len(np.asarray(offset_pc_4_dist.points))

# define point cloud color
green_color = [0, 0, 0]
np_colors_3 = np.array([green_color for _ in range(offset_pc_4_dist_size)])
offset_pc_4_dist.colors = o3d.utility.Vector3dVector(np_colors_3)

In [125]:
if SHOW_PC:
    o3d.visualization.draw_geometries([pcd_2, offset_pc_4_dist])

In [67]:
# merge pc 2 and pc 2 + dist
merged_pc = o3d.geometry.PointCloud()
merged_np_arr = np.concatenate([np.asarray(pcd_2.points), np.asarray(offset_pc_2_dist.points)])

In [68]:
merged_np_arr.shape[0] == np.asarray(pcd_2.points).shape[0] + np.asarray(offset_pc_2_dist.points).shape[0]

True

In [69]:
merged_pc.points = o3d.utility.Vector3dVector(merged_np_arr)
merged_pc_size = len(np.asarray(merged_pc.points))

# define point cloud color
soft_blue_color = [0, 255, 255]
np_colors_merge = np.array([soft_blue_color for _ in range(merged_pc_size)])
merged_pc.colors = o3d.utility.Vector3dVector(np_colors_merge)

# show point cloud info
idx = 'merged'
print(f'PC {idx}:\n', merged_pc, f'\nPC {idx} size: ', merged_pc_size, f'\n\nPC {idx} colors: \n', np.asarray(merged_pc.colors), f'\n\nPC {idx} points:\n', np.asarray(merged_pc.points))

PC merged:
 geometry::PointCloud with 241662 points. 
PC merged size:  241662 

PC merged colors: 
 [[  0. 255. 255.]
 [  0. 255. 255.]
 [  0. 255. 255.]
 ...
 [  0. 255. 255.]
 [  0. 255. 255.]
 [  0. 255. 255.]] 

PC merged points:
 [[79.222       9.426       2.907     ]
 [73.181       9.99        2.707     ]
 [73.124      10.216       2.706     ]
 ...
 [ 3.72431491 -1.396      -1.725     ]
 [ 3.74231491 -1.39       -1.731     ]
 [ 3.75331491 -1.381      -1.735     ]]


In [75]:
if SHOW_PC:
    o3d.visualization.draw_geometries([merged_pc])

In [74]:
points_dict = {tuple(point): 0 for point in np.asarray(pcd.points)}
points_dict

742, 1.008): 0,
 (11.276, 20.733, 1.007): 0,
 (11.204, 20.756, 1.007): 0,
 (11.12, 20.756, 1.005): 0,
 (11.048, 20.778, 1.005): 0,
 (10.967, 20.783, 1.004): 0,
 (10.898, 20.81, 1.003): 0,
 (10.818, 20.818, 1.002): 0,
 (10.776, 20.815, 1.002): 0,
 (10.695, 20.819, 1.001): 0,
 (10.63, 20.854, 1.001): 0,
 (10.546, 20.85, 0.999): 0,
 (10.474, 20.87, 0.999): 0,
 (10.398, 20.882, 0.998): 0,
 (10.323, 20.896, 0.997): 0,
 (10.245, 20.903, 0.996): 0,
 (10.204, 20.901, 0.996): 0,
 (10.127, 20.91, 0.995): 0,
 (10.056, 20.931, 0.994): 0,
 (9.978, 20.937, 0.993): 0,
 (9.906, 20.956, 0.993): 0,
 (9.832, 20.969, 0.992): 0,
 (9.751, 20.967, 0.991): 0,
 (9.701, 20.946, 0.99): 0,
 (9.005, 19.6, 0.939): 0,
 (8.931, 19.601, 0.937): 0,
 (8.873, 19.638, 0.938): 0,
 (8.828, 19.703, 0.939): 0,
 (9.241, 20.803, 0.979): 0,
 (9.231, 20.958, 0.984): 0,
 (9.231, 21.048, 0.986): 0,
 (9.155, 21.055, 0.985): 0,
 (9.088, 21.08, 0.985): 0,
 (9.009, 21.079, 0.984): 0,
 (8.938, 21.096, 0.984): 0,
 (8.861, 21.098, 0.983):

In [139]:
# for each point get the distance to all 
pcd_arr, pcd_2_arr = np.asarray(new_pcd.points), np.asarray(new_pcd_2.points)
# get unique points from both point clouds
pcd_set, pcd_2_set = set(map(tuple, pcd_arr)), set(map(tuple, pcd_2_arr))
# op & returns the intersection of the point clouds
intersec_arr = list(pcd_set & pcd_2_set)
intersec_np = np.array(intersec_arr)  # transform to a numpy array
print('Intersection between PC 1 and PC 2:', intersec_np.shape, '\nPC 1 size:\n', pcd_arr.shape, '\nPC 2 size:\n', pcd_2_arr.shape)

Intersection between PC 1 and PC 2: (173, 3) 
PC 1 size:
 (120574, 3) 
PC 2 size:
 (121604, 3)


In [140]:
# transform the intersection points found into a point cloud format
intersec_pc = o3d.geometry.PointCloud()
intersec_pc.points = o3d.utility.Vector3dVector(intersec_np)
intersec_pc_size = len(np.asarray(intersec_pc.points))

# define point cloud color
green_color = [0, 255, 0]
np_colors_3 = np.array([red_color for _ in range(intersec_pc_size)])

# offset this new point cloud to visualize clearly comparing to pc 1 and pc 2
intersec_pc_offset = o3d.geometry.PointCloud()
intersec_pc_offset.points = o3d.utility.Vector3dVector(np.asarray(intersec_pc.points) + [0.0, 0.0, -20.0])
intersec_pc_offset.colors = o3d.utility.Vector3dVector(np_colors_3)

In [141]:
if SHOW_PC:
    # show both point clouds and the intersection between them:
    # the first map is the first point cloud
    # the second map is the second point cloud
    # the third map is intersection between both point clouds
    o3d.visualization.draw_geometries([pcd, offset_pcd_2, intersec_pc_offset])