In [1]:
import open3d as o3d 
import numpy as np
from pathlib import Path
from scipy.spatial import distance

In [11]:
# get data base path to collect the point clouds
BASE = Path().resolve().parents[1]
DATA_PATH = BASE / 'data'
print(DATA_PATH)
SHOW_PC = True

/home/dayoff/codes/point_cloud_lib/data


In [3]:
# get first point cloud, assign it with a blue color
pc_path = DATA_PATH / 'kitti' / '0000000000.ply'
pcd = o3d.io.read_point_cloud(str(pc_path), format='ply')
pcd_size = len(np.asarray(pcd.points))

# define point cloud color
blue_color = [0, 0, 255]
np_colors = np.array([blue_color for _ in range(pcd_size)])
pcd.colors = o3d.utility.Vector3dVector(np_colors)

# show point cloud info
print('PCD:\n', pcd, '\n', 'PCD size: ', pcd_size, '\n', '\nPCD colors: \n', np.asarray(pcd.colors), '\n', '\nPCD points:\n', np.asarray(pcd.points))

PCD:
 geometry::PointCloud with 120574 points. 
 PCD size:  120574 
 
PCD colors: 
 [[  0.   0. 255.]
 [  0.   0. 255.]
 [  0.   0. 255.]
 ...
 [  0.   0. 255.]
 [  0.   0. 255.]
 [  0.   0. 255.]] 
 
PCD points:
 [[74.536  9.937  2.752]
 [74.558 10.178  2.754]
 [74.569 10.419  2.755]
 ...
 [ 3.705 -1.394 -1.73 ]
 [ 3.611 -1.345 -1.681]
 [ 3.73  -1.377 -1.738]]


In [127]:
if SHOW_PC:
    o3d.visualization.draw_geometries([pcd])

In [4]:
# get second point cloud, assign it with a red color
pc_path = DATA_PATH / 'kitti' / '0000000001.ply'
pcd_2 = o3d.io.read_point_cloud(str(pc_path), format='ply')
pcd_2_size = len(np.asarray(pcd_2.points))

# define point cloud color
red_color = [255, 0, 0]
np_colors_2 = np.array([red_color for _ in range(pcd_2_size)])
pcd_2.colors = o3d.utility.Vector3dVector(np_colors_2)

# show point cloud info
print('PCD 2:\n', pcd_2, '\n', 'PCD 2 size: ', pcd_2_size, '\n', '\nPCD 2 colors: \n', np.asarray(pcd_2.colors), '\n', '\nPCD 2 points:\n', np.asarray(pcd_2.points))

PCD 2:
 geometry::PointCloud with 120831 points. 
 PCD 2 size:  120831 
 
PCD 2 colors: 
 [[255.   0.   0.]
 [255.   0.   0.]
 [255.   0.   0.]
 ...
 [255.   0.   0.]
 [255.   0.   0.]
 [255.   0.   0.]] 
 
PCD 2 points:
 [[79.222  9.426  2.907]
 [73.181  9.99   2.707]
 [73.124 10.216  2.706]
 ...
 [ 3.692 -1.396 -1.725]
 [ 3.71  -1.39  -1.731]
 [ 3.721 -1.381 -1.735]]


In [133]:
if SHOW_PC:
    o3d.visualization.draw_geometries([pcd_2])

In [7]:
# get third point cloud, assign it with a green color
pc_path = DATA_PATH / 'kitti' / '0000000002.ply'
pcd_3 = o3d.io.read_point_cloud(str(pc_path), format='ply')
pcd_3_size = len(np.asarray(pcd_3.points))

# define point cloud color
green_color = [0, 255, 0]
np_colors_3 = np.array([green_color for _ in range(pcd_3_size)])
pcd_3.colors = o3d.utility.Vector3dVector(np_colors_3)

# show point cloud info
print('PCD 3:\n', pcd_3, '\n', 'PCD 3 size: ', pcd_3_size, '\n', '\nPCD 3 colors: \n', np.asarray(pcd_3.colors), '\n', '\nPCD 3 points:\n', np.asarray(pcd_3.points))

PCD 3:
 geometry::PointCloud with 121015 points. 
 PCD 3 size:  121015 
 
PCD 3 colors: 
 [[  0. 255.   0.]
 [  0. 255.   0.]
 [  0. 255.   0.]
 ...
 [  0. 255.   0.]
 [  0. 255.   0.]
 [  0. 255.   0.]] 
 
PCD 3 points:
 [[78.372  8.078  2.873]
 [77.816  9.63   2.861]
 [71.744 10.138  2.659]
 ...
 [ 3.712 -1.397 -1.733]
 [ 3.723 -1.388 -1.737]
 [ 3.737 -1.38  -1.742]]


In [8]:
# offset the second point cloud to visualize it more clearly
offset_pcd_2 = o3d.geometry.PointCloud(pcd_2)
offset_pcd_2.points = o3d.utility.Vector3dVector(np.asarray(offset_pcd_2.points) + [0.0, 0.0, -10.0])
# assign same color to the offset point cloud
offset_pcd_2.colors = o3d.utility.Vector3dVector(np_colors_2)  

In [9]:
# offset the third point cloud to visualize it more clearly
offset_pcd_3 = o3d.geometry.PointCloud(pcd_3)
offset_pcd_3.points = o3d.utility.Vector3dVector(np.asarray(offset_pcd_3.points) + [0.0, 0.0, -20.0])
# assign same color to the offset point cloud
offset_pcd_3.colors = o3d.utility.Vector3dVector(np_colors_3)  

In [12]:
if SHOW_PC:
    o3d.visualization.draw_geometries([pcd, offset_pcd_2, offset_pcd_3])

In [20]:
# merge all 3 point clouds
merged_pc = o3d.geometry.PointCloud()
merged_np_arr = np.concatenate([np.asarray(pcd.points), np.asarray(pcd_2.points), np.asarray(pcd_3.points)])

(362420, 3)

In [21]:
merged_np_arr.shape[0] == np.asarray(pcd.points).shape[0] + np.asarray(pcd_2.points).shape[0] + np.asarray(pcd_3.points).shape[0]

True

In [29]:
merged_pc.points = o3d.utility.Vector3dVector(merged_np_arr)
merged_pc_size = len(np.asarray(merged_pc.points))

# define point cloud color
soft_blue_color = [0, 255, 255]
np_colors_merge = np.array([soft_blue_color for _ in range(merged_pc_size)])
merged_pc.colors = o3d.utility.Vector3dVector(np_colors_merge)

# show point cloud info
idx = 'merged'
print(f'PC {idx}:\n', merged_pc, f'\nPC {idx} size: ', merged_pc_size, f'\n\nPC {idx} colors: \n', np.asarray(merged_pc.colors), f'\n\nPC {idx} points:\n', np.asarray(merged_pc.points))

PC merged:
 geometry::PointCloud with 362420 points. 
PC merged size:  362420 

PC merged colors: 
 [[  0. 255. 255.]
 [  0. 255. 255.]
 [  0. 255. 255.]
 ...
 [  0. 255. 255.]
 [  0. 255. 255.]
 [  0. 255. 255.]] 

PC merged points:
 [[74.536  9.937  2.752]
 [74.558 10.178  2.754]
 [74.569 10.419  2.755]
 ...
 [ 3.712 -1.397 -1.733]
 [ 3.723 -1.388 -1.737]
 [ 3.737 -1.38  -1.742]]


In [32]:
if SHOW_PC:
    o3d.visualization.draw_geometries([merged_pc])

In [139]:
# for each point get the distance to all 
pcd_arr, pcd_2_arr = np.asarray(new_pcd.points), np.asarray(new_pcd_2.points)
# get unique points from both point clouds
pcd_set, pcd_2_set = set(map(tuple, pcd_arr)), set(map(tuple, pcd_2_arr))
# op & returns the intersection of the point clouds
intersec_arr = list(pcd_set & pcd_2_set)
intersec_np = np.array(intersec_arr)  # transform to a numpy array
print('Intersection between PC 1 and PC 2:', intersec_np.shape, '\nPC 1 size:\n', pcd_arr.shape, '\nPC 2 size:\n', pcd_2_arr.shape)

Intersection between PC 1 and PC 2: (173, 3) 
PC 1 size:
 (120574, 3) 
PC 2 size:
 (121604, 3)


In [140]:
# transform the intersection points found into a point cloud format
intersec_pc = o3d.geometry.PointCloud()
intersec_pc.points = o3d.utility.Vector3dVector(intersec_np)
intersec_pc_size = len(np.asarray(intersec_pc.points))

# define point cloud color
green_color = [0, 255, 0]
np_colors_3 = np.array([red_color for _ in range(intersec_pc_size)])

# offset this new point cloud to visualize clearly comparing to pc 1 and pc 2
intersec_pc_offset = o3d.geometry.PointCloud()
intersec_pc_offset.points = o3d.utility.Vector3dVector(np.asarray(intersec_pc.points) + [0.0, 0.0, -20.0])
intersec_pc_offset.colors = o3d.utility.Vector3dVector(np_colors_3)

In [141]:
if SHOW_PC:
    # show both point clouds and the intersection between them:
    # the first map is the first point cloud
    # the second map is the second point cloud
    # the third map is intersection between both point clouds
    o3d.visualization.draw_geometries([pcd, offset_pcd_2, intersec_pc_offset])