In [64]:
import open3d as o3d
import numpy as np

In [65]:
N = 1000
vox_size = 0.1

pts = np.zeros((N, 3))
pts

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
# create an evenly spaced sequence in a specified interval
pts[:, 0] = np.linspace(0, 1, N)
pts

array([[0.      , 0.      , 0.      ],
       [0.001001, 0.      , 0.      ],
       [0.002002, 0.      , 0.      ],
       ...,
       [0.997998, 0.      , 0.      ],
       [0.998999, 0.      , 0.      ],
       [1.      , 0.      , 0.      ]])

In [67]:
pcd = o3d.geometry.PointCloud()
print(pcd)
pcd.points = o3d.utility.Vector3dVector(pts)
print(pcd)

geometry::PointCloud with 0 points.
geometry::PointCloud with 1000 points.


In [68]:
print(pcd.get_min_bound(), end='\n\n\n')
print(pcd.get_max_bound())

[0. 0. 0.]


[1. 0. 0.]


In [69]:
pcd_ds, trace, old_points = pcd.voxel_down_sample_and_trace(
    vox_size, pcd.get_min_bound(), pcd.get_max_bound(), False
)
print(pcd_ds, end='\n\n\n')
print(trace, end='\n\n\n')
print(old_points)

geometry::PointCloud with 11 points.


[[999  -1  -1  -1  -1  -1  -1  -1]
 [949 998  -1  -1  -1  -1  -1  -1]
 [749 799  -1  -1  -1  -1  -1  -1]
 [649 699  -1  -1  -1  -1  -1  -1]
 [549 599  -1  -1  -1  -1  -1  -1]
 [449 499  -1  -1  -1  -1  -1  -1]
 [349 399  -1  -1  -1  -1  -1  -1]
 [849 899  -1  -1  -1  -1  -1  -1]
 [249 299  -1  -1  -1  -1  -1  -1]
 [149 199  -1  -1  -1  -1  -1  -1]
 [ 49  99  -1  -1  -1  -1  -1  -1]]


[IntVector[999], IntVector[900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998], IntVector[700, 701, 702, 703, 704, 705, 706, 707, 

In [70]:
# Offset the new points a little in y so we can see them in the visualization
pcd_ds.points = o3d.utility.Vector3dVector(np.asarray(pcd_ds.points) + [0.0, 0.1, 0.0])
print("N = %d" % (len(pcd.points)))
print("M = %d" % (len(pcd_ds.points)))
print("Trace Shape = ", trace.shape)
print(trace)

o3d.visualization.draw_geometries([pcd, pcd_ds])

N = 1000
M = 11
Trace Shape =  (11, 8)
[[999  -1  -1  -1  -1  -1  -1  -1]
 [949 998  -1  -1  -1  -1  -1  -1]
 [749 799  -1  -1  -1  -1  -1  -1]
 [649 699  -1  -1  -1  -1  -1  -1]
 [549 599  -1  -1  -1  -1  -1  -1]
 [449 499  -1  -1  -1  -1  -1  -1]
 [349 399  -1  -1  -1  -1  -1  -1]
 [849 899  -1  -1  -1  -1  -1  -1]
 [249 299  -1  -1  -1  -1  -1  -1]
 [149 199  -1  -1  -1  -1  -1  -1]
 [ 49  99  -1  -1  -1  -1  -1  -1]]
